[build]
  command = "yarn build"
  publish = "dist"
  ignore = "test $INCOMING_HOOK_URL && echo 'Webhook found' || git diff $CACHED_COMMIT_REF --name-only | egrep '(scripts|styles)'"

[[redirects]]
  from = "/login"
  to = "https://gradebook.app/api/v0/session/begin"

[[redirects]]
  from = "/blog/content/*"
  to = "https://blog.gradebook.app/content/:splat"

[[headers]]
    for = "/built/*"
    [headers.values]
    Cache-Control = "public max-age=63072000" # 2 years (thanks, cachebusting!)
