[build]
  command = "yarn build"
  publish = "dist"
  ignore = "sh ./should-build.sh"

[[redirects]]
  from = "/login"
  to = "https://gradebook.app/api/v0/session/begin"

[[redirects]]
  from = "/blog/content/*"
  to = "https://blog.gradebook.app/blog/content/:splat"

[[redirects]]
  from = "/assets/*"
  to = "https://static.gradebook.app/sYbR9JXKTI/:splat"

[[redirects]]
  from = "/favicon.ico"
  to = "https://static.gradebook.app/sYbR9JXKTI/favicon.ico"
  status = 200 # No need to redirect for this

[[redirects]]
  from = "/my"
  to = "https://the.gradebook.app/my/"

[[redirects]]
  from = "/my/:splat"
  to = "https://the.gradebook.app/my/:splat"

[[redirects]]
  from = "/blog/p/:splat"
  to = "/preview-helper/"
  status = 200 # The preview helper depends on the url to be a preview url

[[headers]]
    for = "/built/*"
    [headers.values]
    Cache-Control = "public max-age=63072000" # 2 years (thanks, cachebusting!)
