[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "https://gradebook.app/api/v0/session/begin"

[[redirects]]
  from = "/blog/content/*"
  to = "https://blog.gradebook.app/content/:splat"
