[build]
  command = "yarn build"
  publish = "dist"
  ignore = "./should-build.sh"

[[redirects]]
  from = "/login"
  to = "https://gradebook.app/api/v0/session/begin"

[[redirects]]
  from = "/blog/content/*"
  to = "https://blog.gradebook.app/content/:splat"

[[headers]]
    for = "/built/*"
    [headers.values]
    Cache-Control = "public max-age=63072000" # 2 years (thanks, cachebusting!)
