[build]
  command = "yarn build"
  publish = "dist"
  ignore = "sh ./should-build.sh"

[[redirects]]
  from = "/login"
  to = "https://gradebook.app/api/v0/session/begin"

[[redirects]]
  from = "/blog/content/*"
  to = "https://blog.gradebook.app/blog/content/:splat"
  status = 200
  headers = {Host = "https://www.gradebook.app"}

[[headers]]
    for = "/built/*"
    [headers.values]
    Cache-Control = "public max-age=63072000" # 2 years (thanks, cachebusting!)
